// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsfrIVZyLEhEMbErvCtUjiys9Vd03j_V8',
    appId: '1:956760737493:web:7c1a692b139bd7dfc1c45c',
    messagingSenderId: '956760737493',
    projectId: 'agrobebadb',
    authDomain: 'agrobebadb.firebaseapp.com',
    storageBucket: 'agrobebadb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDDMaFQcPE7zSNK5Een2zWkGmOluQSAfo',
    appId: '1:956760737493:android:f8fc73e01486e517c1c45c',
    messagingSenderId: '956760737493',
    projectId: 'agrobebadb',
    storageBucket: 'agrobebadb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoMD7Q6g98toIKhSq3mvh8NgnSg4bswpI',
    appId: '1:956760737493:ios:b2312f785aca1c0dc1c45c',
    messagingSenderId: '956760737493',
    projectId: 'agrobebadb', 
    storageBucket: 'agrobebadb.appspot.com',
    iosBundleId: 'com.example.agrobeba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoMD7Q6g98toIKhSq3mvh8NgnSg4bswpI',
    appId: '1:956760737493:ios:b2312f785aca1c0dc1c45c',
    messagingSenderId: '956760737493',
    projectId: 'agrobebadb',
    storageBucket: 'agrobebadb.appspot.com',
    iosBundleId: 'com.example.agrobeba',
  );
}
